### PR TITLE
477 prepare for netbox 4.0

### PR DESCRIPTION
**Pull request by mattieserver**

### CODE REVIEW

**Comment by vishnubraj** [comment]
Hello, @mattieserver  @dreng  is this completed? When will this get released?
is there any way I can help get this done?

**Comment by Creepios** [comment]
Hi, I have found a bug. The error always appears when you want to display the topology. Following error in browser console:
image

**Comment by dreng** [comment]
> is there any way I can help get this done?

Oh yes! Just have a look at the checklist in issue #477. If you like to contribute, go for it!

**Comment by mattieserver** [comment]
The search functionality does not work like it should.

When `default_renderer = forms.renderers.DjangoTemplates()` is not in the forms.py the custom filters are not applied when pressing the search option. 
Example: I have the show_unconnected & show_cables on in the Individual Options, when i go to the topology i see the filters are active but i still have to press the search button to show the graph. When i click the search button the 2 options are gone and thus no graph is shown. If i select other options from netbox itself like site, region, those are then present after clicking search.

If we do not remove `default_renderer = forms.renderers.DjangoTemplates()`, the search button looks like this:
image
Other fields that are also broken:
image

**Comment by ibuclaw** [comment]
> The search functionality does not work like it should.
> 
> When `default_renderer = forms.renderers.DjangoTemplates()` is not in the forms.py the custom filters are not applied when pressing the search option. Example: I have the show_unconnected & show_cables on in the Individual Options, when i go to the topology i see the filters are active but i still have to press the search button to show the graph. When i click the search button the 2 options are gone and thus no graph is shown. If i select other options from netbox itself like site, region, those are then present after clicking search.
> 
> If we do not remove `default_renderer = forms.renderers.DjangoTemplates()`, the search button looks like this

Also the checkbox buttons are all over the place.

I've raised it as a bug in upstream (https://github.com/netbox-community/netbox/issues/16293) - it's obvious what the cause is, and you can _sort of_ mitigate it by turning on the (experimental) HTMX navigation feature in user preferences.

I'm opined to think that the appropriate fix would be for upstream to add the hidden input only if HTMX is enabled, but I don't have a good sense of how these templates piece together.

**Comment by ibuclaw** [comment]
> I'm opined to think that the appropriate fix would be for upstream to add the hidden input only if HTMX is enabled, but I don't have a good sense of how these templates piece together.

Otherwise these will have to be replaced with a `NullBooleanField` with a binary `None`/`True` choice, along with all the logic fix-ups that come with it.

**Comment by natm** [comment]
https://linear.app/netboxlabs/issue/ENG-2990/

**Comment by ibuclaw** [comment]
> Otherwise these will have to be replaced with a `NullBooleanField` with a binary `None`/`True` choice, along with all the logic fix-ups that come with it.

The only response I've gotten from upstream is that the use of BooleanField in searches being broken is not their problem. So migrating to NullBooleanField seems to be the only way out of this.

**Comment by dreng** [comment]
> The only response I've gotten from upstream is that the use of BooleanField in searches being broken is not their problem.

Very disappointing. Anyway, thanks for trying.

**Comment by mattieserver** [comment]
Yeah, with NullBooleanField it seems to work

**Pull request merged**
