### PR TITLE
Topology button in Site View

### PR DESCRIPTION
**Pull request by renatoalmeidaoliveira**
Add topology button in site view using the htmx modal.
Sample
image

### CODE REVIEW

**Comment by renatoalmeidaoliveira** [comment]
Fixes #191

**Comment by mattieserver** [comment]
Will test this in the weekend and then merge.

But we might have to change the default filter if #188 also get merged.

**Comment by dreng** [comment]
@renatoalmeidaoliveira
Nice work. Is it possible to add an icon to the "Topology" button? Otherwise it looks a bit inhomogeneous together with the buttons "Clone", "Edit" and "Delete". The existing button for cable trace could fit.

**Comment by renatoalmeidaoliveira** [comment]
@dreng added mdi icons as in the image
image

**Comment by dreng** [comment]
> @dreng added mdi icons as in the image 
That's better, thank you. But why do the buttons look so different? The text in the buttons for topology and close are well centered vertically whereas the other ones don't. Is it deceptive or does the font look larger?

**Comment by renatoalmeidaoliveira** [comment]
@dreng figure out what it is, my buttons doesn't had the class btn-sm, gonna add it now

**Comment by renatoalmeidaoliveira** [comment]
@dreng 
image

**Pull request merged**
