### PR TITLE
Fixes #406: 70 pixels wasting (unused) space at the bottom

### LINKED ISSUE #406: 70 pixels wasting (unused) space at the bottom
### NetBox version

v3.6.3

### Topology Views version

v3.8.0

### Steps to Reproduce

1. Look at the bottom:)

### Expected Behavior

Network diagram should use all the space from top (filter labels) to bottom (status bar icons).

### Observed Behavior

There is 70 pixels gap between diagram area and the top of the status bar icons. This margin is too huge and not in line with three other ones.

Screenshot_20231014_042537

**Browser:** Chromium Version 118.0.5993.70 (Official Build) Arch Linux (64-bit).
**Resolution:** 1920x1200.

### PR DESCRIPTION
**Pull request by dreng**
After trying to solve the issue with plain CSS, I ended up writing Javascript functions in order to determine the available height. A resize listener calls these functions witch modify the CSS on the fly.

I also decided to add a thin border around the canvas. This makes clear which parts of the tab content belong to the canvas.

### CODE REVIEW

**Comment by mattieserver** [comment]
I am not sure we should fix it like this.
While your code works i would like it just to be css and i am not sure its worth it for just a few users.

**Comment by dreng** [comment]
I agree that a pure css solution would be nicer. I just wasted another day to solve the issue like this. Unfortunately I didn't manage to fix it with using flex boxes, respectively bootstrap classes like d-flex, flex-direction-column and flex-grow-1. The display messed up in some way, whatever I tried. Either the flex box didn't do a proper job when resizing the window or the canvas was also displayed on the filter tab. The latter is always the case if you change the "networks" div from "display: block" into "display: flex", which is needed in order to let a nested div grow automatically. I don't know why this happens and it doesn't make sense to me.

I don't agree that the change is for just a few users. In fact, everyone is affected. The further you move away from the 16:9 format, the worse the result: The gap will get bigger, the canvas will not fully be displayed or the footer moves out of the window. We should take care of different display sizes, display formats and display orientations. To put it another way: it should be responsive design.

**Comment by mattieserver** [comment]
Some of the javascript was commited in a wrong branch i think.
https://github.com/mattieserver/netbox-topology-views/pull/419/files on the file netbox_topology_views/templates/netbox_topology_views/index.html

also, changes for the ccs, have to be in the static_dev folder

**Comment by dreng** [comment]
Hi @mattieserver ,
it's no problem to resolve the css mistake and to rebranch. In your last statement, you didn't sound like you want to implement this PR. Just gimme some feedback if you changed your mind. If you did, I'm gonna fix this PR. Otherwise we should close it.

**Comment by mattieserver** [comment]
Hi,

I don't see an other fix for now, so we might as well implement it like you suggested.

**Pull request closed without merging**
