### PR TITLE
disable physics if not saving coords

### PR DESCRIPTION
**Pull request by dainok**
I had issues in the following two scenarios:

1. not saving coordinates, but coordinates are previously saved: current behavior physics=True, expected physics=False
2. saving coordinates but nodes doesn't have a saved one: current behavior physics=True, expected physics=False

Let me know if that make sense for you.

### CODE REVIEW

**Comment by dainok** [comment]
Hi @mattieserver I would like to know if you are open to more PR.

**Comment by dainok** [comment]
Sorry @mattieserver my mistake during the commit. Should be fine now.

**Comment by dainok** [comment]
Seems the file is changed in the meanwhile, I have to review. I'll ping you in a few days.

**Comment by dainok** [comment]
@mattieserver should be fine now. Let me know if you can resolve conflicts.

I also added preselected_device_roles to the __init__ file. If it's not configured in configuration.py you get an error about the missing parameter.

**Comment by dainok** [comment]
@mattieserver let me know if you can merge it or if you prefer that I create a new one.

**Comment by mattieserver** [comment]
Hi,

Can you create a new PR? With the changes in the main branch it become somewhat unclear what changes you want to make.

**Comment by dainok** [comment]
Moving to https://github.com/mattieserver/netbox-topology-views/pull/139

**Pull request closed without merging**
