### PR TITLE
#14, added circuit terminations

### PR DESCRIPTION
**Pull request by mattieserver**

### CODE REVIEW

**Comment by martydingo** [comment]
I still do not see circuit terminations. 

I know the update was successful as now I have a lot of different colors too. 

I should see my circuit connecting the two DC's we have presence in, but they still appear disconnected on the map with no link between the patch panels at either end.

**Comment by mattieserver** [comment]
Have you set the "enable_circuit_terminations" to True in the plugin settings? It defaults to False

**Comment by martydingo** [comment]
Right, sorry, that's showed some progress.

However it's broken the topology view. 

On a request:
```
Internal Server Error: /api/plugins/topology-views/search/search/
Traceback (most recent call last):
  File "/srv/netbox/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/srv/netbox/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/srv/netbox/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/netbox/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/netbox/venv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/netbox/venv/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/srv/netbox/venv/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/srv/netbox/venv/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/srv/netbox/venv/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/netbox/venv/lib/python3.7/site-packages/netbox_topology_views/api/views.py", line 181, in search
    edge["from"] = cable.termination_a.circuit.termination_a.cable.termination_b.device.id
AttributeError: 'CircuitTermination' object has no attribute 'device'
```

**Comment by martydingo** [comment]
We are currently building this up, hence why some Circuit's may not have devices. 

Some won't, also, it'd force a design choice to create a device to represent upstream carriers, whereas the preferable option would be a choice, representation of the 'internet' with upstream provider names which could hold IX names and Tier [1-3] ISP names, or not show it at all.

**Pull request merged**
