### PR TITLE
Implement l3 topology diagram

### PR DESCRIPTION
**Pull request by dainok**
I'm adding a second diagram to build L3 topologies (Idepends on https://github.com/mattieserver/netbox-topology-views/pull/139).

The idea is:
* I can get per VRF L3 diagrams (additional filter compared to L2 diagrams)
* For each "prefix" (network) the diagram attach devices with L3 interfaces attached to
* Devices are named "devicename-vrfname" (a single device can route multiple VRF)
* The VRF is the one associated to the "prefix" not the one associated to interfaces (they can differ)

It should be tested on additional scenarios, on mine it's working fine.

VRF leaking is not supported.

@mattieserver let me know if it can be interesting for you.

### CODE REVIEW

**Comment by mattieserver** [comment]
Looks interesting

**Comment by dainok** [comment]
Hi @mattieserver I realize there is another conflict. Do you think the PR could be helpful for you? Should I make another PR to fix the conflict?

**Comment by mattieserver** [comment]
There are some changes since the update to netbox 3.3.
I will try to resolve the issues and then look to merge it.

**Comment by dainok** [comment]
Thank you, let me know if I can help.

**Comment by dainok** [comment]
@mattieserver sorry for the delay. I made an assumption: a prefix is defined for each network. I didn't found any other viable option to get the configured networks and used IP address.

Based on that, I think the super scope is not useful, because it is a sort of summarization of multiple networks.
What do you think?

**Comment by mattieserver** [comment]
Yes, i need to fix some stuff and now with the recent MR/PR's there are some new issues. 
I might recreate the branch to be up to date since i think i borked the rebase/git history.

**Pull request closed without merging**
