### PR TITLE
Update to support netbox v3

### PR DESCRIPTION
**Pull request by mattieserver**
See #72

### CODE REVIEW

**Comment by m-dsouza** [comment]
Hello, Will this plugin update be available to the github community to be make a pull request to use as the template error persist for version higher 3

**Comment by nemmeviu** [comment]
+1

**Comment by joaolucasmacedo** [comment]
Looking forward do see Topology Vies compatible with NetBox v3.0 and 3.1.
It is the best plugin ever!

**Comment by mattieserver** [comment]
New PR for v3.1: #82

**Comment by joaolucasmacedo** [comment]
> New PR for v3.1: #82

How can I install the new PR? I'm using Netbox 3.1.8

**Comment by mattieserver** [comment]
Hi,

I still need to create the release.
I will do this later today or tomorrow.
I will also give a short description on how you can install the 'beta' release.

**Comment by mattieserver** [comment]
You can install the latest version with:
`pip install netbox-topology-views==1.0.0a1`

Or add netbox-topology-views==1.0.0a1 to the (local)_requirements.txt file.
And then run `pip3 install -r local_requirements.txt`

**Pull request closed without merging**
